export { default as POIMap } from './components/poi-map'
export { default as GeoCohortMap } from './components/geo-cohort-map'
export { default as QLReportMap } from './components/ql-report-map'
export { default as LocusMap } from './components/locus-map'
export { default as GeoJSONMap } from './components/geojson-map'
export { default as HexagonMap } from './components/hexagon-map'
export { default as ReportMap } from './components/report-wi-map'
